spring.application.name=editr-api

# Cookie
editr.session.cookie-secure=false

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/editr
spring.datasource.username=editr
spring.datasource.password=editr

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
